### PR TITLE
Add Forecaster abstract class and NeuralNetForecaster implementation

### LINKED ISSUE #6: Class for NN forecasting
We should have a class for doing NN forecasts in core.problems

### LINKED ISSUE #7: General forecaster class
We should have a general forecaster class in core.utilities that all specific forecasters subclass.

### PR DESCRIPTION
**Pull request by juliohm**
Fix #6 and #7

This is just an initial draft, could you please review and make sure everything matches the original idea? I will then rewrite the neural network regression in terms of this interface.

### CODE REVIEW

**Comment by juliohm** [comment]
I've finished porting the neural net to the forecaster interface as well. However, the `problem.calc_mse()` function is returning a higher value now in the notebook. I will push the notebook so that you can test it locally as well.

**Comment by bmeyers** [comment]
I think the abstract forecaster class should reside in utilities rather than problems. That seems to make more sense to me. What do you think?

**Comment by bmeyers** [comment]
The abstract forecaster class is missing some attributes, but other than that it looks like the right idea.

**Comment by juliohm** [comment]
I think it deserves its own file like I did forecaster.py? Let me know if
you prefer it to be in utilities and I'll move it there ;)

**Comment by bmeyers** [comment]
I was actually thinking it made sense to have the NN forecaster in problems along with arima and functional regression. Why does it need its own module?

**Comment by juliohm** [comment]
I think by breaking each regressor on its own file we reduce the number of
dependencies on the user side. Right now we have to have all those
libraries installed even if we don't use some of them.

**Comment by bmeyers** [comment]
That makes a lot of sense. Thanks!

**Comment by juliohm** [comment]
This is good to go. Merging and preparing for a new re-write with TensorFlow only for more flexibility.

**Pull request merged**
